spring:
  application:
    name: demoCours
  datasource:
    #url: jdbc:mysql://mysql-app-millenium.cpgkkimmelee.us-east-2.rds.amazonaws.com:3306/app_cursos?useSSl=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    #: root
    #password: admin1234
    url: jdbc:mysql://localhost:3306/management_courses_3
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:

    hibernate.ddl-auto: update



##spring.application.name=demoCours

##Amazon s3



