spring:
  application:
    name: demoCours
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate.ddl-auto: validate
    open-in-view: false
logging:
  level:
    org.hibernate.SQL: info

##spring.application.name=demoCours

##Amazon s3



